# Tomcat
server:
  port: 9210

# Spring
spring:
  application:
    # 应用名称
    name: ruoyi-auth
  profiles:
    # 环境配置
    active: @profiles.active@

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        namespace: ${spring.profiles.active}
        username: nacos
        password: nacos
        group: @nacos.discovery.group@
      config:
        namespace: ${spring.profiles.active}
        username: nacos
        password: nacos
        group: @nacos.config.group@
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:${spring.application.name}.yml
