server:
  port: 8800
  servlet:
    context-path: /easy-retry

spring:
  application:
    name: ruoyi-easyretry-server
  profiles:
    active: @profiles.active@
  web:
    resources:
      static-locations: classpath:admin/

mybatis-plus:
  typeAliasesPackage: com.aizuda.easy.retry.template.datasource.persistence.po
  global-config:
    db-config:
      table-prefix: er_
      where-strategy: NOT_EMPTY
      capital-mode: false
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  config: classpath:logback-plus.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: ./logs/${spring.application.name}/console.log

--- # nacos 配置
spring:
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        namespace: ${spring.profiles.active}
        group: @nacos.discovery.group@
        metadata:
          # 解决 er 服务有 context-path 无法监控问题
          management.context-path: ${server.servlet.context-path}/actuator
      config:
        namespace: ${spring.profiles.active}
        group: @nacos.config.group@
  config:
    import:
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml
