datasource:
  # 有默认值，强烈建议更换 https://www.kancloud.cn/tracy5546/dynamic-datasource/2280963
  public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAL9nJk/ewysgKEonFZ95vJJ8Dps+JTNYcly5aNYoJKq6TsoVey6c8Z7PZwn9xMdyjC2X9wWBO8BKg5h4j5/DBDsCAwEAAQ==
  system-master:
    # jdbc 所有参数配置参考 https://lionli.blog.csdn.net/article/details/122018562
    # rewriteBatchedStatements=true 批处理优化 大幅提升批量插入更新删除性能
    url: jdbc:mysql://139.196.208.53:3306/ruoyi-plus?useUnicode=true&characterEncoding=utf8&useSSL=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: Zs11195310
  job:
    url: jdbc:mysql://139.196.208.53:3306/ruoyi-job?useUnicode=true&characterEncoding=utf8&useSSL=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: Zs11195310

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 加密秘钥
      public-key: ${datasource.public-key}
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: true
      # 严格模式 匹配不到数据源则报错
      strict: true
      hikari:
        # 最大连接池数量
        maxPoolSize: 20
        # 最小空闲线程数量
        minIdle: 10
        # 配置获取连接等待超时的时间
        connectionTimeout: 30000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 600000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 1800000
        # 多久检查一次连接的活性
        keepaliveTime: 30000
