spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      seata: false
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${datasource.job.url}
          username: ${datasource.job.username}
          password: ${datasource.job.password}

# powerjob 配置
powerjob:
  worker:
    enabled: true
    # 需要先在 powerjob 登录页执行应用注册后才能使用
    app-name: ${spring.application.name}
    # 29203 端口 随着主应用端口飘逸 避免集群冲突
    port: 2${server.port}
    # 单个任务追加的工作流上下文最大长度，超过这个长度的会被直接丢弃，默认值 8192
    max-appended-wf-context-length: 4096
    # 任务返回结果信息的最大长度，超过这个长度的信息会被截断，默认值 8192
    max-result-length: 4096
    # 通讯协议，4.3.0 开始支持 HTTP 和 AKKA 两种协议，官方推荐使用 HTTP 协议（注意 server 和 worker 都要开放相应端口）
    protocol: http
    # 调度服务器地址，IP:Port 或 域名，多值逗号分隔
    # server-address: 127.0.0.1:7700
    # 调度中心应用名 通过服务名连接调度中心(启用 server-name 会导致 server-address 不生效)
    server-name: ruoyi-powerjob-server
    # 持久化方式，可选，默认 disk
    store-strategy: disk

easy-retry:
  enabled: true
  # 需要在EasyRetry后台组管理创建对应名称的组,然后创建任务的时候选择对应的组,才能正确分派任务
  group-name: "ruoyi_group"
  # EasyRetry接入验证令牌
  token: "ER_cKqBTPzCsWA3VyuCfFoccmuIEGXjr5KT"
  server:
    # 从 nacos 获取服务
    server-name: ruoyi-easyretry-server
    # 服务名优先 ip垫底
    host: 127.0.0.1
    port: 1788
  # 详见 script/sql/easy_retry.sql `er_namespace` 表
  namespace: ${spring.profiles.active}
