spring:
  security:
    user:
      name: ruoyi
      password: 123456
  boot:
    admin:
      ui:
        title: RuoYi-Cloud-Plus服务监控中心
        brand: <span>Service Monitoring Center</span>
      discovery:
        # seata 不具有健康检查的能力 防止报错排除掉
        ignored-services: seata-server
