spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 开启seata代理，开启后默认每个数据源都代理，如果某个不需要代理可单独关闭
      seata: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: ${datasource.system-master.url}
          username: ${datasource.system-master.username}
          password: ${datasource.system-master.password}

--- # elasticsearch 功能配置
# 文档地址: https://www.easy-es.cn/
# 更改包名需要去 EasyEsConfiguration 修改包扫描(后续版本支持配置文件读取)
easy-es:
  # es连接地址+端口 格式必须为ip:port,如果是集群则可用逗号隔开
  address : 139.196.208.53:9200
  # 注意ES建议使用账号认证 不使用会报警告日志
  #如果无账号密码则可不配置此行
  username: elastic
  #如果无账号密码则可不配置此行
  password: Zs195310

mail:
  enabled: true
  host: smtp.163.com
  port: 465
  # 是否需要用户名密码验证
  auth: true
  # 发送方，遵循RFC-822标准
  from: zs11195310@163.com
  # 用户名（注意：如果使用foxmail邮箱，此处user为qq号）
  user: zs11195310@163.com
  # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
  pass: RQTSNZQRVNDUJDNB
  # 使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。
  starttlsEnable: true
  # 使用SSL安全连接
  sslEnable: true
  # SMTP超时时长，单位毫秒，缺省值不超时
  timeout: 0
  # Socket连接超时值，单位毫秒，缺省值不超时
  connectionTimeout: 0

# sms 短信 支持 阿里云 腾讯云 云片 等等各式各样的短信服务商
# https://sms4j.com/doc3/ 差异配置文档地址 支持单厂商多配置，可以配置多个同时使用
sms:
  # 配置源类型用于标定配置来源(interface,yaml)
  config-type: yaml
  # 用于标定yml中的配置是否开启短信拦截，接口配置不受此限制
  restricted: true
  # 短信拦截限制单手机号每分钟最大发送，只对开启了拦截的配置有效
  minute-max: 1
  # 短信拦截限制单手机号每日最大发送量，只对开启了拦截的配置有效
  account-max: 30
  # 以下配置来自于 org.dromara.sms4j.provider.config.BaseConfig类中
  blends:
    # 自定义的标识，也就是configId这里可以是任意值
    alibaba:
      # 厂商标识，标定此配置是哪个厂商，详细请看厂商标识介绍部分
      supplier: alibaba
      # 阿里云accessKey
      access-key-id: JENC(s1r98KDzV5Jc3d/ucFMNOWgOADCDnIwBgQ/3qosbK7QxALW2IxQfTY36EaZ1ZasJQRtCNCF2beqLe3DfOV95pQ==)
      # 阿里云accessKeySecret
      access-key-secret: JENC(erXeLnBSsF0ZdL4bv9GU/w/6SZm4FWU+/u5Gc6djtZvCW/jSIaTnyzFFsI4d7Aqe2pkfdGUo7UtYf+CUqOR7Sw==)
      # 阿里云短信签名
      signature: 周帅个人博客
      # 模板ID
      template-id: SMS_270350279
      # 模板变量名称
      template-name: code
      # 短信自动重试间隔时间  默认五秒
      retry-interval: 5
      # 短信重试次数，默认0次不重试，如果你需要短信重试则根据自己的需求修改值即可
      max-retries: 3
      # 当前厂商的发送数量上限，默认不设置上限
      maximum: 100

# seata配置
seata:
  # Seata 事务组编号，用于 TC 集群名
  tx-service-group: demo_tx_group
  # vgroup-mapping下一定要有一个对应tx-service-group的映射，映射到default（seata默认的集群名称）
  service:
    vgroup-mapping:
      demo_tx_group: default

# jasypt加密,默认ENC,为了和dynamic区分，重命名
jasypt:
  encryptor:
    property:
      prefix: JENC(
      suffix: )
  test:
    value: JENC(gOTHk9bNOaUvAjzsESWGca02P5A8Kao9QVL9Y15uioSh56pm2dNZs7xFoDZC5kn0)
