spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${datasource.job.url}
    username: ${datasource.job.username}
    password: ${datasource.job.password}
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: easy_retry
      max-lifetime: 1800000

# easy-retry 服务端配置
easy-retry:
  # 拉取重试数据的每批次的大小
  retry-pull-page-size: 1000
  # 拉取重试数据的每批次的大小
  job-pull-page-size: 1000
  # 服务端 netty 端口
  netty-port: 1788
  # 重试和死信表的分区总数
  total-partition: 2
  # 一个客户端每秒最多接收的重试数量指令
  limiter: 1000
  # 号段模式下步长配置
  step: 100
  # 日志保存时间(单位: day)
  log-storage: 90
  # 回调配置
  callback:
    #回调最大执行次数
    max-count: 288
    #间隔时间
    trigger-interval: 900
  mode: all
  retry-max-pull-count: 10
