version: '3'

services:
  ruoyi-gateway:
    image: 139.196.208.53:5000/alibaba/ruoyi-gateway:2.1.1
    container_name: ruoyi-gateway
    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SW_AGENT_NAME: ruoyi-gateway
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "139.196.208.53:11800"
      JAVA_OPTS: "-Dspring.profiles.active=dev -Xms256m -Xmx256m"
    ports:
      - "18080:8080"
    volumes:
      # 时间和时区
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      # skywalking 探针
      - ruoyi-agent-config:/skywalking/agent/config
      # 日志文件目录
      - ~/logs/ruoyi/ruoyi-gateway:/logs/ruoyi/ruoyi-gateway
    privileged: true

  ruoyi-auth:
    image: 139.196.208.53:5000/alibaba/ruoyi-auth:2.1.1
    container_name: ruoyi-auth
    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SW_AGENT_NAME: ruoyi-auth
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "139.196.208.53:11800"
      JAVA_OPTS: "-Dspring.profiles.active=dev -Xms256m -Xmx256m"
    ports:
      - "9210:9210"
    volumes:
      # 时间和时区
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      # skywalking 探针
      - ruoyi-agent-config:/skywalking/agent/config
      # 日志文件目录
      - ~/logs/ruoyi/ruoyi-auth:/logs/ruoyi/ruoyi-auth
    privileged: true

  ruoyi-system:
    image: 139.196.208.53:5000/alibaba/ruoyi-system:2.1.1
    container_name: ruoyi-system
    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SW_AGENT_NAME: ruoyi-system
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "139.196.208.53:11800"
      JAVA_OPTS: "-Dspring.profiles.active=dev -Xms256m -Xmx256m"
    ports:
      - "9201:9201"
    volumes:
      # 时间和时区
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      # skywalking 探针
      - ruoyi-agent-config:/skywalking/agent/config
      # 日志文件目录
      - ~/logs/ruoyi/ruoyi-system:/logs/ruoyi/ruoyi-system
    privileged: true

  ruoyi-gen:
    image: 139.196.208.53:5000/alibaba/ruoyi-gen:2.1.1
    container_name: ruoyi-gen
    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SW_AGENT_NAME: ruoyi-gen
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "139.196.208.53:11800"
      JAVA_OPTS: "-Dspring.profiles.active=dev -Xms256m -Xmx256m"
    ports:
      - "9202:9202"
    volumes:
      # 时间和时区
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      # skywalking 探针
      - ruoyi-agent-config:/skywalking/agent/config
      # 日志文件目录
      - ~/logs/ruoyi/ruoyi-gen:/logs/ruoyi/ruoyi-gen
    privileged: true

  ruoyi-job:
    image: 139.196.208.53:5000/alibaba/ruoyi-job:2.1.1
    container_name: ruoyi-job
    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SW_AGENT_NAME: ruoyi-job
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "139.196.208.53:11800"
      JAVA_OPTS: "-Dspring.profiles.active=dev -Xms256m -Xmx256m"
    ports:
      - "9203:9203"
    volumes:
      # 时间和时区
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      # skywalking 探针
      - ruoyi-agent-config:/skywalking/agent/config
      # 日志文件目录
      - ~/logs/ruoyi/ruoyi-job:/logs/ruoyi/ruoyi-job
    privileged: true

  ruoyi-resource:
    image: 139.196.208.53:5000/alibaba/ruoyi-resource:2.1.1
    container_name: ruoyi-resource
    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SW_AGENT_NAME: ruoyi-resource
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: "139.196.208.53:11800"
      JAVA_OPTS: "-Dspring.profiles.active=dev -Xms256m -Xmx256m"
    ports:
      - "9204:9204"
    volumes:
      # 时间和时区
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      # skywalking 探针
      - ruoyi-agent-config:/skywalking/agent/config
      # 日志文件目录
      - ~/logs/ruoyi/ruoyi-resource:/logs/ruoyi/ruoyi-resource
    privileged: true

volumes:
  ruoyi-agent-config:
